sudo: false

branches:
  only: deploy

language: node_js

install:
  - git submodule -q update --init
  - npm install

script:
  - npm run tslint
  - npm test
  - node ./scripts/prebuild

os:
  - osx
  - linux

node_js:
  - "10"
