environment:
  matrix:
    - nodejs_version: 8.10.0
      platform: x64

os: Visual Studio 2017

install:
  - echo $env "%PLATFORM%"
  - IF /I "%PLATFORM%" == "x86" SET PATH=C:\python27;%PATH%
  - IF /I "%PLATFORM%" == "x64" SET PATH=C:\Python27-x64;%PATH%
  - IF /I "%PLATFORM%" == "x86" CALL "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - IF /I "%PLATFORM%" == "x64" CALL "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - ps: Install-Product node $env:nodejs_version
  - npm i npm@latest -g
  - git submodule -q update --init
  - node --version
  - npm --version
  - node -e "console.log(process.arch);"
  - npm install

cache:
  - node_modules

test_script:
  - npm test

build: OFF
deploy: OFF      