environment:
  matrix:
    - nodejs_version: 8
      platform: x64

os: Visual Studio 2015

install:
  - ps: Install-Product node $env:nodejs_version x64
  - node --version
  - npm install

cache:
  - node_modules

test_script:
  - npm test

build: OFF
deploy: OFF