environment:
  matrix:
    - nodejs_version: 8
      platform: x64

os: Visual Studio 2015

install:
  - cmd: git submodule -q update --init
  - node --version
  - npm install
  - npm i npm@latest -g

cache:
  - node_modules

test_script:
  - npm test

build: OFF
deploy: OFF