environment:
  matrix:
    - nodejs_version: 8.10.0
      platform: x64

os: Visual Studio 2015

install:
  - Install-Product node $env:nodejs_version
  - npm i npm@latest -g
  - git submodule -q update --init
  - node --version
  - npm install

cache:
  - node_modules

test_script:
  - npm test

build: OFF
deploy: OFF      